server:
  port: 8090
spring:
  application:
    name: user-consume
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启Spring Cloud重试
eureka:
  client:
    fetch-registry: true #是否拉取其他服务信息，默认是true
    register-with-eureka: true #是否注册自己的信息到EurekaService中，默认是true
    service-url: #Eureka-Serve的地址，如果是集群需要添加其他Server的地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    ################################服务消费者默认从eureka中获取服务列表的频率##########################################
    registry-fetch-interval-seconds: 8 #默认`每隔30秒`会重新获取并更新数据
  instance:
    prefer-ip-address: true #当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 #指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}
    ##默认格式是：`${hostname} + ${spring.application.name} + ${server.port}`
logging:
  level:
    org.springframework: debug
    com.netflix.discovery.DiscoveryClient: debug #显示拉取服务列表日志
    com.gyoomi: info
################################Ribbon重试功能配置#################################################
user-service:
  ribbon:
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 2 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
##################################Hystrix配置###############################################################
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000 #设置hystrix的超时时间为6000ms
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enable: false
#        isolation:
#          thread:
#            timeoutInMillisecond: 100000 #设置hystrix的超时时间为6000ms
################################Feign配置#############################################################
feign:
  compression:
    request:
      enabled: true #开启请求压缩
      mime-type: text/html,application/xml,application/json #设置压缩的数据类型
      min-request-size: 2048 #设置触发压缩的大小下限
    response:
      enabled: true #开启响应压缩
  hystrix:
    enabled: true #开启Feign的熔断功能

###########actuator配置##############################################
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  #开放所有页面节点  默认只开启了health、info两个节点
      base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改


